New York Times article page feauture
Elbie-em/New_York_Times_article_page_clone pull request #2
Opened 2020-01-23 19:53 UTC by enelesmai

- Added the nav bar 
- Added main article sections
- Added aside section
- Added inner articles
- Added embedded video
- Added extras section
-Added footer

2020-01-23 20:53 UTC, mosesogwo commented on index.html
> +                <div style="clear: both;"></div>
remove inline styles

2020-01-23 20:53 UTC, mosesogwo commented on index.html
> +                <div style="clear:both"></div>
Remove inline style

2020-01-23 20:56 UTC, mosesogwo requested changes
**Great job team :+1:. A few changes and you can :airplane:**

1. The content of your page below the featured image (the article body) is not centered on the page. Check the positioning on the original page and adjust yours to match. It should be centered.

2. In the **More in Space and Astronomy section**, each article thumbnail with the title should be a clickable link.

3. Adjust the alignment of the article list in the **Most Popular section** so that the left margin is well aligned.

**Yours:**
![image](https://user-images.githubusercontent.com/46611870/73022488-fdbfad00-3e29-11ea-8b63-fbfebef953a1.png)

**Original:**
![image](https://user-images.githubusercontent.com/46611870/73022524-0f08b980-3e2a-11ea-96e2-e2051afaf8fb.png)

3. There is a fixed footer on the original page. Please include it on your own page.
![image](https://user-images.githubusercontent.com/46611870/73022601-3495c300-3e2a-11ea-9330-c25cc57f0a2b.png)

4. Remove inline styles from your html markup. It is bad practice.

5. You should remove the Acknowledgements section in your README if there is no one you are acknowledging for this project.

**Kindly make these adjustments and submit another code review request.**

**Cheers:smile:**

**Status: Changes requested**

2020-01-23 20:56 UTC, mosesogwo commented on index.html
> +                <div style="clear:both"></div>
Remove inline style

2020-01-24 00:01 UTC, Forison requested changes
## Status Require Changes🛑
Hi team🙌,
You have done a good job so far. You have also implemented some of the changes raised in the previous review. Let address these issues so we can get this project approved
* [x] Files not related to the project should not be committed and added to .gitignore (e.g. .DS_Store) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
* [x]  Some parts of the page is missing, let us add them
![Screenshot from 2020-01-23 18-52-28](https://user-images.githubusercontent.com/29695661/73033958-9990ef00-3e11-11ea-938d-518d781e690b.png)
* [x] Let us center our main page more than it is now.
## That is it kindly make these changes submit the project for review
### Happy coding💻.
### Addo Forison

2020-01-24 19:38 UTC, enelesmai commented
Main page centered and the index added

2020-01-24 20:29 UTC, addod19 approved these changes
## Status: Approved :100: 

Hi TEAM, congratulations on implementing the changes requested by previous reviewers. Your project looks great :+1: 

You can now merge to master and submit project completion form :smile: 
Happy coding :computer: 

Daniel Larbi Addo

2020-01-24 20:35 UTC, merged